inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['it', 'describe', 'context', 'let', 'specify']

AllCops:
  TargetRubyVersion: 2.3
